Rudder notifications plugin
---------------------------

This project is part of Rudder - IT automation and compliance made easy.
See: https://www.rudder.io/ for more information.

Mailing list, irc :
https://www.rudder-project.org/site/community/mailing-lists/

// Everything after this line goes into Rudder documentation
// ====doc====

= Notification

This plugin aims at providing non-compliance notification modules for
your Rudder server. It currently supports e-mail, slack
notifications and tickets opening in GLPI.

== Installation

* Your Rudder server must have python-requests and python-configparser
installed. (either by your favorite package manager or python module installer)
* Install the package on the Rudder server :
  `/opt/rudder/bin/rudderpkg install-file <plugin>.rpkg`
* Edit the configuration file in `/opt/rudder/etc/notify.conf`. This
config file sets which notifications are enabled and some additional
parameters.

== Usage

The plugin has to be started as a daemon and will watch for
non-compliances on your Rudder infrastructure. Start it with
`systemctl start rudder-notify`.

The plugins takes its config from `/opt/rudder/etc/notify.conf`. Edit this
file to your preferences.

For the e-mail plugin, the plugin uses the `mail` utility to send its
notifications. This program needs to be installed and properly set up.
The e-mail notifications can be set in the conf file to not spam you,
and send by batches of a certain period for you to set. The conf file
also contains the recipients of the e-mails.

The `slack` module needs slack webhooks to be able to send slack messages
to users or channels. You will have to declare an app for your workspace
and create these webhooks via your slack admin panel. More info here :
https://api.slack.com/incoming-webhooks

The plugin can also be configured to open ticket in GLPI based on non-compliance in Rudder.
To do so, in `/opt/rudder/etc/notify.conf`, set the GLPI plugin `on` and fulfill the required parameters.

* `userToken` can be found in the `Users settings` page in the GLPI interface under the `APIToken` field.
* `apiToken` and `url` can be found under the `Setup -> General -> API` pagae in the GLPI interface.

== Authors

Normation http://normation.com
Victor Querette victor.querette@normation.com

== Contributing

Thank you for your interest in our project !
The contribution process is detailed here:
https://www.rudder-project.org/site/documentation/how-to-contribute/

