sudo: required

services:
  - docker

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - ZABBIX_VERSION: 2
  - ZABBIX_VERSION: 3

before_install:
 - curl -L https://github.com/docker/compose/releases/download/1.4.1/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin
 - pushd tests/data/Zabbix${ZABBIX_VERSION} && docker-compose up -d
 - popd

install:
  - pip install coveralls pycodestyle

script:
  - while ! nc -z 127.0.0.1 10051; do sleep 1; done
  - sleep 60
  - pycodestyle --ignore=E501,W504 pyzabbix/
  - pycodestyle tests/*.py
  - coverage run setup.py test

after_success:
  coveralls

notifications:
  email:
    - alexey.dubkov@gmail.com
    - maksim77ster@gmail.com
