#!/usr/bin/python3

import json
import re
import os, sys
import subprocess
import uuid

def makeJsonFile(filename, content):
  os.makedirs(os.path.dirname(filename), exist_ok=True)
  with open(filename, "w") as fd:
    fd.write(json.dumps(content, sort_keys=True, indent=2, separators=(',', ': ')))

def mergeDicts(x, y):
    z = x.copy()
    z.update(y)
    return z

def getSections(path):
    command  = ["/usr/bin/pdftotext",  path, "-"]
    output = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, universal_newlines=True).stdout
    pattern = re.findall(r"(\d\.\d\.\d\.\d\s+[\w ]{5,})\((?:Scored|Unscored)\)", output)
    print(pattern)

def parsePDF(path):
    command  = ["/usr/bin/pdftotext",  path, "-"]
    output = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, universal_newlines=True).stdout
    r = re.compile(r"""(?P<id>(?:\d+\.)+\d+)\s+(?P<name>(?:([\S ]{5,})\n?([\S ])?))\(Scored\)\s*
Profile\s+Applicability:\s+(?:\d+ \| P a g e\s+)?(?:\W+Level\s+(?P<server>1|2)[\s-]+Server)?(?:\s+\W+Level\s+(?P<workstation>1|2)[\s-]+Workstation)?\s+(?P<description>Description:[\S \n]+?)(?=Audit|Remediation)""")
    items = [m.groupdict() for m in r.finditer(output)]
    for iItem in items:
        for k,v in iItem.items():
            if v is not None:
                iItem[k] = v.rstrip("\n").strip()
    return items

def getTagsFromPDF(items, itemName, osName):
    tags = []
    for iItem in items:
        if iItem["name"] in itemName.strip():
            # items number
            ids = iItem["id"].split(".")
            tags.append({"cis-" + osName: ids[0]})
            for i in range(1,len(ids)):
                ids[i] = ids[i-1] + "." + ids[i]
                tags.append({"cis-" + osName: ids[i] })

            # server level
            if iItem["server"] is not None:
                tags.append({"cis-server":  iItem["server"]})
            # workstation level
            if iItem["workstation"] is not None:
                tags.append({"cis-workstation": iItem["workstation"]})
            return tags
    return None

def is_directive(data):
    if "techniqueName" in data and "techniqueVersion" in data:
        return True
    return False

def is_rule(data):
    if "directives" in data and "targets" in data:
        return True
    return False

def is_technique(data):
    if "type" in data and "version" in data and "data" in data:
        return True
    return False

def writeCis(items, path, osName):
    with open(path) as f:
        data = json.load(f)
    if is_directive(data) == True:
        tags = getTagsFromPDF(items, data["displayName"], osName)
        if tags is not None:
            for iDict in tags:
                if iDict not in data["tags"]:
                    data["tags"].append(iDict)
        description = list(filter(lambda x: x.get("name") in data["displayName"], items))
        if description != []:
            data["longDescription"] = description[0]["description"]
        if data["displayName"].startswith("CIS - ") == False:
            data["displayName"] = "CIS - " + data["displayName"]
        data["policyMode"] = "audit"
        makeJsonFile(path, data)

def writeAllCis(basePath, pdfPath, osName):
    items = parsePDF(pdfPath)
    for root, dirs, files in os.walk(basePath):
        for file in files:
            if file.endswith('.json'):
                writeCis(items, os.path.join(root, file), osName)

def getDirectives(basePath):
    directives = []
    for root, dirs, files in os.walk(basePath):
        for file in files:
            if file.endswith('.json'):
               with open(os.path.join(root, file)) as f:
                   data = json.load(f)
               if is_directive(data) == True:
                   directives.append(data)
    return directives

def getRules(basePath):
    rules = []
    for root, dirs, files in os.walk(basePath):
        for file in files:
            if file.endswith('.json'):
               with open(os.path.join(root, file)) as f:
                   data = json.load(f)
               if is_rule(data) == True:
                   rules.append(data)
    return rules

def getTechniques(basePath):
    techniques = []
    for root, dirs, files in os.walk(basePath + "/techniques"):
        for file in files:
            if file.endswith('.json'):
               with open(os.path.join(root, file)) as f:
                   data = json.load(f)
               if is_technique(data) == True:
                   techniques.append(file)
    return techniques

def findMissing(basePath, pdfPath):
    RED = '\033[91m'
    ENDC = '\033[0m'
    GREEN = '\033[92m'

    items = parsePDF(pdfPath)
    directives = getDirectives(basePath)
    # Some items are split in multiples directives, marked with a ( xxxx ) displayname suffix
    for iDirective in directives:
        if re.match(r".*\(.*\)$", iDirective["displayName"]):
            iDirective["displayName"] = re.sub("\s+\(.*\)$", "", iDirective["displayName"])
    implemented = set([i["displayName"].replace("CIS - ", "") for i in directives])

    expected = set([i["name"] for i in items])
    result = list(expected - implemented)

    for i in items:
        if i["name"] in implemented:
            print(GREEN + "[OK]   " + i["id"] + " - " + i["name"] + ENDC)
        else:
            print(RED + "[FAIL] " + i["id"] + " - " + i["name"] + ENDC)
    print("%s items covered out of %s"%(len(implemented), len(expected)))

def trackRules(basePath):
    try:
        with open("packaging/cis.json") as f:
            data = json.load(f)
    except:
        data = {}
    data["rules"] = [i["id"] for i in getRules(basePath)]
    makeJsonFile("packaging/cis.json", data)

def trackDirectives(basePath):
    try:
        with open("packaging/cis.json") as f:
            data = json.load(f)
    except:
        data = {}
    data["directives"] = [i["id"] for i in getDirectives(basePath)]
    makeJsonFile("packaging/cis.json", data)

def trackTechniques(basePath):
    try:
        with open("packaging/cis.json") as f:
            data = json.load(f)
    except:
        data = {}
    data["techniques"] = getTechniques(basePath)
    makeJsonFile("packaging/cis.json", data)

def trackConfig(basePath):
    trackRules(basePath)
    trackDirectives(basePath)
    trackTechniques(basePath)

# Generate rule for a given os based on a benchmark pdf
def generateRule(basePath, pdfPath, osType):
    items = parsePDF(pdfPath)
    expectedDirectives = set([i["name"] for i in items])
    directives = getDirectives(basePath)
    try:
        with open(basePath + "/rules/" + osType + ".json") as f:
            data = json.load(f)
    except:
        rudderUUID = str(uuid.uuid4())
        data = {
                "directives": [],
                "displayName": "CIS - " + osType + " sample rule",
                "enabled": True,
                "id": rudderUUID,
                "longDescription": "",
                "shortDescription": "",
                "system": False,
                "tags": [],
                "targets": [ {"exlude": { "or": [] }, "include": { "or": ["policyServer:root"] } } ]
                }
    data["directives"] = []
    for iDirective in directives:
        if any(elem in iDirective["displayName"].replace("CIS - ", "") for elem in expectedDirectives):
            data["directives"].append(iDirective["id"])
    makeJsonFile(basePath + "/rules/" + osType + ".json", data)

def removeTags(basePath):
    for root, dirs, files in os.walk(basePath):
        for file in files:
            if file.endswith('.json'):
               with open(os.path.join(root, file)) as f:
                   data = json.load(f)
               data["tags"] = []
               makeJsonFile(os.path.join(root, file), data)

targets = [
              { "basePath": "configuration",
                "pdfPath": "pdfs/cis_debian9.pdf",
                "osName": "debian9"
              },

              { "basePath": "configuration",
                "pdfPath": "pdfs/cis_redhat7.pdf",
                "osName": "redhat7"
              }
          ]

# clean tags
removeTags("configuration")

for iRule in targets:
    m = re.search("pdfs/cis_(.*)\.pdf", iRule["pdfPath"])
    osName = m.group(1)
    # Generate rule from pdf and directives
    generateRule(iRule["basePath"], iRule["pdfPath"], osName)
    # Add CIS infos like tags, description, etc...
    writeAllCis(iRule["basePath"], iRule["pdfPath"], osName)
    # Print items coverage
    findMissing(iRule["basePath"], iRule["pdfPath"])

trackConfig("configuration")
