[default.extend-words]
monitord = "monitord"
Ser = "Ser"
unser = "unser"
# False positive on the OAUTHv2 string
OAUT = "OAUT"

# All exceptions below should be removed when upstream will be fixed
includeSytem = "includeSytem"
Sytem = "Sytem"
cssPsuedoElementExclusion = "cssPsuedoElementExclusion"
Psuedo = "Psuedo"
criterias = "criterias"
Formater = "Formater"
Provid = "Provid"
Optionnal = "Optionnal"