#!/bin/bash

set -ex

test_shell()
{
  mkdir -p .shellcheck
  find . \( -path ./.git -prune -o -path ./cis/src/pdfs -prune \) -o -type f -exec grep -Eq '^#!(.*/|.*env +)(sh|bash|ksh)' {} \; -print |
    while IFS="" read -r file
    do
      # collect all warnings
      shellcheck --format=checkstyle "$file" > .shellcheck/$(basename ${file}).log || true
      # fail on >=error
      shellcheck --severity error "$file"
    done
}

# fails on error and ignores other levels
test_shell_error()
{
  # Shellcheck
  find . \( -path ./.git -prune -o -path ./cis/src/pdfs -prune \) -o -type f -exec grep -Eq '^#!(.*/|.*env +)(sh|bash|ksh)' {} \; -print |
    while IFS="" read -r file
    do
      # with recent shellcheck, "-S error" replaces this hack
      # kept as this runs on machines running rudder-dev
      shellcheck --format gcc "$file" | grep " error: " && exit 1 || true
    done
}

# fails on error and ignores other levels
test_python_error()
{
  PYLINT="pylint"
  if type pylint3 >/dev/null; then
    PYLINT="pylint3"
  fi
  find . ! -name ipaddress.py -name '*.py' | xargs ${PYLINT} -E --persistent=n --disable=C,R,import-error,no-member,no-name-in-module
}

test_typos()
{
  # json file below has a name which looks like a typo in its first part, skipping it
  typos --exclude '*.css' --exclude '*-6a9f-4865-a837-95a6a0c49f04.json'
}

if [ "$1" = "--python" ]; then
  test_python_error
elif [ "$1" = "--typos" ]; then
  test_typos
elif [ "$1" = "--shell" ]; then
  test_shell
else
  test_shell_error
  test_python_error
fi
