#!/bin/bash
set -e

test_python()
{
  find . -name '*.py' | xargs -r grep -L "#\!/usr/bin/python3" | grep -v share/python | grep -v zabbix | xargs -r pylint -E --disable=C,R,undefined-variable  --persistent=n --init-hook="sys.path[0:0] = ['./centreon/share/python']"
  find . -name '*.py' | xargs -r grep -l "#\!/usr/bin/python3" | grep -v share/python | grep -v zabbix | xargs -r pylint3 -E --disable=C,R,undefined-variable  --persistent=n
}

test_typos()
{
  # json file below has a name which looks like a typo in its first part, skipping it
  typos --exclude '*.css' --exclude '*-6a9f-4865-a837-95a6a0c49f04.json'
}


if [ "$1" = "--python" ]; then
  test_python
  exit 0
elif [ "$1" = "--typos" ]; then
  test_typos
  exit 0
else
  test_python
  exit 0
fi
