#!/bin/bash
set -e

find . -name '*.py' | xargs -r grep -L "#\!/usr/bin/python3" | grep -v share/python | grep -v zabbix | xargs -r pylint -E --disable=C,R,undefined-variable  --persistent=n --init-hook="sys.path[0:0] = ['./centreon/share/python']"
find . -name '*.py' | xargs -r grep -l "#\!/usr/bin/python3" | grep -v share/python | grep -v zabbix | xargs -r pylint3 -E --disable=C,R,undefined-variable  --persistent=n
