#!/bin/sh

CONFFILE="/opt/rudder/etc/centreon.conf"

mkdir -p /var/rudder/plugin-resources
echo "*/2 * * * * root /opt/rudder/bin/centreon-plugin.py commit" > /etc/cron.d/centreon-rudder

# create configuration file
if [ ! -f "${CONFFILE}" ]
then
  cat > "${CONFFILE}" <<EOF
[CENTREON]
username = YOUR_CENTREON_USERNAME
password = YOUR_CENTREON_PASSWORD
centreonWebserviceURL = http://YOUR_CENTREON_SERVER/centreon
centreonPoller = CENTREON_POLLER

[RUDDER]
# Fill this if the plugin is not installed on the Rudder server
#rudderAPIURL = https://YOUR_RUDDER_SERVER/rudder/api/latest
#rudderAPIToken = YOUR_RUDDER_API_TOKEN

# Put here IP networks that you don't want to appear in centreon (space separated)
#ipBlacklist = 10.0.0.0/8 192.168.0.0/16
EOF
fi
