#!/bin/sh

CONFFILE="/opt/rudder/etc/centreon.conf"

mkdir -p /var/rudder/plugin-resources
echo "*/2 * * * * root /opt/rudder/bin/centreon-plugin apply-configuration >/dev/null" > /etc/cron.d/centreon-rudder

# create configuration file
if [ ! -f "${CONFFILE}" ]
then
  cat > "${CONFFILE}" <<EOF
[CENTREON]
username = YOUR_CENTREON_USERNAME
password = YOUR_CENTREON_PASSWORD
centreonWebserviceURL = http://YOUR_CENTREON_SERVER/centreon
# default poller
centreonPoller = CENTREON_POLLER
# Add this template automatically to all hosts added via Rudder
# For a more fine grained choice, pleas use https://docs.rudder.io/reference/current/reference/generic_methods.html#monitoring_template
defaultTemplate = generic-active-host-custom

[RUDDER]
# Fill this if the plugin is not installed on the Rudder server
#rudderAPIURL = https://YOUR_RUDDER_SERVER/rudder/api/latest
#rudderAPIToken = YOUR_RUDDER_API_TOKEN

# Put here IP networks that you don't want to appear in centreon (space separated)
#ipBlacklist = 10.0.0.0/8 192.168.0.0/16

[POLLERS]
# a relay can be given a poller, every node behind theis relay is assigned to this poller
#relay1 = poller1

# alternatively, call this script to determine which poller to associate
# will be called: ./poller-script hostname uuid
#poller-script = /usr/local/bin/poller-script

EOF
fi
