# Plugin for GLPI and Rudder

This project is part of Rudder - IT infrastructure Automation and Compliance.
See: http://rudder.io for more information.

See repository main README for information about licensing, contribution, and
other general information.

// Everything after this line goes into Rudder documentation
// ====doc====
[glpi-plugin]
= GLPI

This plugin provides integration between Rudder and GLPI. It will send
to your GLPI server the up-to-date inventories processed by the Rudder
server.

== Installation

* Install a https://glpi-project.org/[GLPI server]. The server is not
required to be running on the same host as the Rudder server. However,
this plugin has to be installed and running on the Rudder server.
* Install the
https://github.com/fusioninventory/fusioninventory-for-glpi/releases[fusion inventory plugin for GLPI]
* Install the glpi plugin on your Rudder server
* Edit the configuration file in `/opt/rudder/etc/glpi.conf`. This config
file must contain the URL to your GLPI server’s fusion inventory plugin.

== Usage

Run `/opt/rudder/bin/glpi-plugin send-all` to update all the inventories.
This command is run automatically everyday around 7AM.

To manuallyi update an inventory for a specific node, run `/opt/rudder/bin/glpi-plugin send-one UUID`.
The plugin will automatically send a new inventory upon node
addition to Rudder.

NOTE: All nodes inventories are sent daily to GLPI, including pending nodes.
