#
# make all will build node-external-reports.rpkg. 
# make demo will build a license limited version of the plugin
#

include ../common-scala-plugin.mk

plugin: all

# this plugin has no resources to install
plugin-resources:
	# nothing to cp into target$(NAME)
	# example could be: 
	#cp src/main/resources/helloworld.properties target/$(NAME)/


