#!/bin/bash
CONFIGURATION_PATH=/var/rudder/packages/rudder-plugin-cis

SOURCE_DIR=${CONFIGURATION_PATH}/techniques
CONFIG_REPO=/var/rudder/configuration-repository
CATEGORY="CIS plugin"
C_CATEGORY=$(echo $CATEGORY | sed "s/[^a-zA-Z0-9_]/_/g")
FOLDERS="ncf/30_generic_methods/cis techniques/$C_CATEGORY techniques/ncf_techniques"

mkdir -p $CONFIG_REPO/techniques/$C_CATEGORY

cat <<EOT > $CONFIG_REPO/techniques/$C_CATEGORY/category.xml
<xml>
  <name>$CATEGORY</name>
  <description>
    Techniques from the CIS plugin
  </description>
</xml>
EOT


for file in $SOURCE_DIR/*; do
  BASE=$(echo $file | sed "s/.*\///" | sed "s/\.[^.]*$//")
  C_BASE=$(echo $BASE | sed "s/[^a-zA-Z0-9_]/_/g")
  mkdir -p $CONFIG_REPO/techniques/$C_CATEGORY/$C_BASE
  cd $CONFIG_REPO/techniques/ncf_techniques && ln -rs $CONFIG_REPO/techniques/$C_CATEGORY/$C_BASE && cd -
done

# Import Generic Methods
cd $CONFIG_REPO
git reset
for file in $FOLDERS
do
  chown -R root:rudder $file
  chmod 664 -R $file
  chmod -R +X $file
  git add $file
done
git commit -m "CIS plugin installation"


# Import Techniques
${CONFIGURATION_PATH}/rudder-synchronize import technique ${CONFIGURATION_PATH}/techniques
rudder server reload-techniques

# Import Directives
${CONFIGURATION_PATH}/rudder-synchronize import directive ${CONFIGURATION_PATH}/directives

# Import Rules
${CONFIGURATION_PATH}/rudder-synchronize import rule ${CONFIGURATION_PATH}/rules
