#!/bin/bash
CONFIG_REPO=/var/rudder/configuration-repository
CATEGORY="{category}"
C_CATEGORY=$(echo $CATEGORY | sed "s/[^a-zA-Z0-9_]/_/g")
FOLDERS="ncf/30_generic_methods/cis techniques/${C_CATEGORY}"
CONFIGURATION_PATH="/var/rudder/packages/rudder-plugin-{plugin-id}"
RUDDER_BIN="/opt/rudder/bin"

mkdir -p $CONFIG_REPO/techniques/$C_CATEGORY

cat <<EOT > $CONFIG_REPO/techniques/$C_CATEGORY/category.xml
<xml>
  <name>$CATEGORY</name>
  <description>
    Techniques from the CIS plugin
  </description>
</xml>
EOT


cd $CONFIG_REPO
git reset
for file in $FOLDERS
do
  chown -R root:rudder $file
  chmod 664 -R $file
  chmod -R +X $file
  git add $file
done
git commit -m "CIS plugin installation"

# Import GM
echo "Reloading methods library"
curl --silent -k --header "Content-type: application/json"   --header "X-API-Token: $(cat /var/rudder/run/api-token)" --request POST https://localhost/rudder/api/latest/methods/reload | jq '.result'

# Import Techniques
${RUDDER_BIN}/rudder_synchronize.py import technique ${CONFIGURATION_PATH}/techniques

# Import Directives
${RUDDER_BIN}/rudder_synchronize.py import directive ${CONFIGURATION_PATH}/directives

# Import Rules
${RUDDER_BIN}/rudder_synchronize.py import rule ${CONFIGURATION_PATH}/rules
