#!/bin/bash
set -xe
NAME="{plugin-id}"
PLUGIN_FOLDER="/var/rudder/packages/rudder-plugin-${NAME}"

# Remove techniques
$PLUGIN_FOLDER/remove_configuration configuration $PLUGIN_FOLDER $PLUGIN_FOLDER/trackFile.json
rudder server reload-techniques

## Remove plugin categories
cd /var/rudder/configuration-repository
git reset
$PLUGIN_FOLDER/remove_configuration categories "{category}"
git commit -m "Removing $NAME plugin categories"
# We need to restore archive when deleting a category, otherwise the active tree is not synchronized correctly
curl -k -X POST -H "X-API-Token: $(cat /var/rudder/run/api-token)" https://localhost/rudder/api/latest/system/archives/directives/restore/latestCommit
rudder server reload-techniques
