#!/bin/bash

# SPDX-License-Identifier: CC-BY-SA-2.0
# SPDX-FileCopyrightText: 2013-2020 Normation SAS

# @description promote a node to relay
# @man Promote a node to relay by using scale-out-relay plugin API
# @man +
# @man *Arguments*:
# @man +
# @man *UUID*: node ID to promote

. "${BASEDIR}/../lib/common.sh"

RUDDER_OPT=/opt/rudder
RUDDER_VAR=/var/rudder
RUDDER_JSON="${RUDDER_VAR}/cfengine-community/inputs/rudder.json"
SYSTEM_TOKEN=$(cat /var/rudder/run/api-token)

rudder_json_value() {
	jq -r ".$1" ${RUDDER_JSON}
}

if [ -f "${RUDDER_JSON}" ]; then
  RUDDER_VERIFY_CERTIFICATES=$(rudder_json_value 'RUDDER_VERIFY_CERTIFICATES')
fi

if [ "${RUDDER_VERIFY_CERTIFICATES}" = "true" ]
then
  CERTIFICATE_OPTION=""
else
  CERTIFICATE_OPTION="--insecure"
fi

DOWNLOAD_COMMAND="curl --silent --show-error ${CERTIFICATE_OPTION} --globoff"

usage() {
	echo "Usage: $0 <UUID of the node to make a relay server>"
}

RELAY_UUID=$1

# Check arguments
if [ "${RELAY_UUID}" = "" ]; then
	echo "ERROR: Need the UUID of the Relay server as an argument, aborting."
	usage
	exit 1
elif [ "${RELAY_UUID}" = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeee" ]; then
	echo "ERROR: Please use a real UUID, not the one supplied in the documentation, aborting."
	exit 1
fi

echo "Rudder relay installation script starting, using UUID ${RELAY_UUID}."

# Scale-out-relay API call (must have the plugin installed)
API_URL="http://127.0.0.1:8080/rudder/api/latest"
response=$(${DOWNLOAD_COMMAND} --location --proxy '' --header "X-API-Token: ${SYSTEM_TOKEN}" --request POST "${API_URL}/scaleoutrelay/promote/${RELAY_UUID}")
code=$?

if [ ${code} -ne 0 ]; then
	 echo "Failed to promote ${RELAY_UUID} to relay. Code ${code}" 1>&2
	 exit 1
fi

result_api=$(echo "$response" | jq -r '.result')
parse_response=$?

if [ "${result_api}" = "error" ]; then
	echo "ERROR: Promote ${RELAY_UUID} have failed" 1>&2
	error_details=$(echo "$response" | jq -r '.errorDetails')
	echo "Reason: ${error_details}"
	exit 1
elif [ ${parse_response} = 4 ];then
	echo "ERROR: Unknown response format, parsing failed. Code ${parse_response}" 1>&2
else
	echo "Done."

	echo -n "INFO: Triggering promises generation..."
	${DOWNLOAD_COMMAND} --location --proxy '' --header "X-API-Token: ${SYSTEM_TOKEN}" --request POST -k "${API_URL}/system/reload/techniques"
	echo " Done."

	echo "Success: all steps completed successfully."
	exit 0
fi
