#!/bin/bash

# SPDX-License-Identifier: CC-BY-SA-2.0
# SPDX-FileCopyrightText: 2013-2020 Normation SAS

# @description promote a node to relay
# @man Promote a node to relay by using scale-out-relay plugin API
# @man +
# @man *Arguments*:
# @man +
# @man *UUID*: node ID to promote

. "${BASEDIR}/../lib/common.sh"

RUDDER_OPT=/opt/rudder
RUDDER_VAR=/var/rudder

DOWNLOAD_COMMAND="curl --silent --show-error --globoff"

usage() {
	echo "Usage: $0 <UUID of the node to make a relay server>"
}

RELAY_UUID=$1

TRIGGER_AGENT_RUN=false

while getopts "r" opt; do
  case $opt in
    r)
      TRIGGER_AGENT_RUN=true
      ;;
  esac
done


# Check arguments
if [ "${RELAY_UUID}" = "" ]; then
	echo "ERROR: Need the UUID of the Relay server as an argument, aborting."
	usage
	exit 1
elif [ "${RELAY_UUID}" = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeee" ]; then
	echo "ERROR: Please use a real UUID, not the one supplied in the documentation, aborting."
	exit 1
fi

echo "Rudder relay installation script starting, using UUID ${RELAY_UUID}."

# Scale-out-relay API call (must have the plugin installed)
API_URL="http://127.0.0.1:8080/rudder/api/latest"
response=$(${DOWNLOAD_COMMAND} --location --proxy '' --header @/var/rudder/run/api-token-header --request POST "${API_URL}/scaleoutrelay/promote/${RELAY_UUID}")
code=$?

if [ ${code} -ne 0 ]; then
	 echo "Failed to promote ${RELAY_UUID} to relay. Code ${code}" 1>&2
	 exit 1
fi

result_api=$(echo "$response" | jq -r '.result')
parse_response=$?

if [ "${result_api}" = "error" ]; then
	echo "ERROR: Promote ${RELAY_UUID} have failed" 1>&2
	error_details=$(echo "$response" | jq -r '.errorDetails')
	echo "Reason: ${error_details}"
	exit 1
elif [ ${parse_response} = 4 ];then
	echo "ERROR: Unknown response format, parsing failed. Code ${parse_response}" 1>&2
else
	echo "Done."

	echo -n "INFO: Triggering promises generation..."
	${DOWNLOAD_COMMAND} --location --proxy '' --header @/var/rudder/run/api-token-header --request POST -k "${API_URL}/system/reload/techniques"
	echo " Done."

    if [ "$TRIGGER_AGENT_RUN" = true ]; then
	    echo -n "INFO: Triggering agent run on relay ${RELAY_UUID}..."
	    ${DOWNLOAD_COMMAND} --location --proxy '' --header @/var/rudder/run/api-token-header --request POST -k "${API_URL}/nodes/${RELAY_UUID}/applyPolicy"
	    echo " Done."
    fi

	echo "Success: all steps completed successfully."
	exit 0
fi
