#!/bin/bash
set -e

CONFFILE="/opt/rudder/etc/zabbix.conf"
CRONFILE="/etc/cron.d/zabbix-rudder"

mkdir -p /var/rudder/plugin-resources

# create cron file
cat > "${CRONFILE}" <<EOF
0 * * * * root /opt/rudder/bin/zabbix-plugin.py update
*/2 * * * * root /opt/rudder/bin/zabbix-plugin apply-configuration >/dev/null
EOF

# create configuration file
if [ ! -f "${CONFFILE}" ]; then
  cat > "${CONFFILE}" <<EOF
[ZABBIX]
username = YOUR_ZABBIX_USERNAME
password = YOUR_ZABBIX_PASSWORD
ZabbixWebserviceURL = http://

[RUDDER]
rudderAPIURL = https://localhost/rudder/api/latest
rudderAPIToken = YOUR_RUDDER_API_TOKEN
EOF
fi
