#!/bin/bash
set -x
PLUGIN_FULL_NAME="rudder-plugin-ansible-policies"
PRETTY_NAME="Ansible Policies"
CONFIGURATION_PATH=/var/rudder/packages/$PLUGIN_FULL_NAME

# Code below should be mostly comon between the plugins
SOURCE_DIR=${CONFIGURATION_PATH}/techniques
CONFIG_REPO=/var/rudder/configuration-repository

CATEGORY="$PRETTY_NAME plugin"
C_CATEGORY=$(echo $CATEGORY | sed "s/[^a-zA-Z0-9_]/_/g")
FOLDERS="techniques/$C_CATEGORY"

mkdir -p $CONFIG_REPO/techniques/$C_CATEGORY

cat <<EOT > $CONFIG_REPO/techniques/$C_CATEGORY/category.xml
<xml>
  <name>$CATEGORY</name>
  <description>
    Techniques from the $CATEGORY
  </description>
</xml>
EOT

# Import Generic Methods
cd $CONFIG_REPO
git reset
for file in $FOLDERS
do
  git add $file
done
git commit -m "$CATEGORY installation"
/opt/rudder/bin/rudder-fix-repository-permissions

# Make extra scripts executables
chmod +x $CONFIGURATION_PATH/rudder-synchronize $CONFIGURATION_PATH/ansible.sh $CONFIGURATION_PATH/remove_configuration

# Import Techniques
curl --silent -k --header "Content-type: application/json" --header "X-API-Token: $(cat /var/rudder/run/api-token)" --request PUT https://localhost/rudder/api/latest/techniques --data "@${CONFIGURATION_PATH}/techniques/ansible_policies.json"
