#!/bin/bash
set -e
CONFIGURATION_PATH=/opt/rudder/share/plugins/openscap

# Import Techniques
curl --silent --insecure --header "X-API-TOKEN: $(cat /var/rudder/run/api-token)" --request POST https://localhost/rudder/api/latest/archives/import --form "archive=@${CONFIGURATION_PATH}/openscap_technique.zip"
