#!/bin/bash
set -x
PLUGIN_FULL_NAME="rudder-plugin-openscap-policies"
PLUGIN_NAME="openscap-policies"
PRETTY_NAME="OpenSCAP Policies"
CONFIGURATION_PATH=/var/rudder/packages/$PLUGIN_FULL_NAME
CATEGORY="$PRETTY_NAME plugin"
C_CATEGORY=$(echo $CATEGORY | sed "s/[^a-zA-Z0-9_]/_/g")

git reset
# Remove technique
$CONFIGURATION_PATH/remove-configuration

# Remove techniques symlink and ncf ones
cd /var/rudder/configuration-repository

TECHNIQUES=$(jq -r '.techniques[]' $CONFIGURATION_PATH/$PLUGIN_NAME.json | sed "s%^%$CONFIGURATION_PATH/techniques/%" | xargs jq -r '.data.bundle_name')
for file in $TECHNIQUES; do
  git rm -rf --ignore-unmatch techniques/ncf_techniques/$file
  git rm -rf --ignore-unmatch ncf/50_techniques/$file
done;

# Remove category
cd /var/rudder/configuration-repository/techniques
git rm -rf $C_CATEGORY
git commit -m "OpenSCAP-report plugin uninstallation"

rudder server reload-techniques

