#!/bin/bash
set -e

su - rudder-webapp <<EOF
# Force policy regeneration at restart
touch /opt/rudder/etc/trigger-policy-generation
EOF
cp /opt/rudder/share/plugins/scale-out-relay/server-node-to-relay /opt/rudder/share/commands/
cp /opt/rudder/share/plugins/scale-out-relay/server-relay-to-node /opt/rudder/share/commands/
echo "Plugin scale-out-relay successfully installed"
