#!/bin/bash
set -e
# Force policy regeneration at restart
touch /opt/rudder/etc/trigger-policy-generation
cp /opt/rudder/share/plugins/scale-out-relay/server-node-to-relay /opt/rudder/share/commands/
