#!/bin/bash

# Force policy regeneration at restart
touch /opt/rudder/etc/trigger-policy-generation
cp /opt/rudder/share/plugins/scale-out-relay/server-node-to-relay /opt/rudder/share/commands/
cp /opt/rudder/share/plugins/scale-out-relay/server-relay-to-node /opt/rudder/share/commands/
